export const project_list = [
  { stack: ["reactjs"], key: 1, name: "covid_19", description: "", link: "" },
  {
    stack: ["reactjs"],
    key: "2",
    name: "amazon_clone",
    description: "",
    link: "",
  },
  { stack: ["reactjs"], key: 3, name: "netflix", description: "", link: "" },
  { stack: ["reactjs"], key: 4, name: "spotify", description: "", link: "" },
  { stack: ["reactjs"], key: 5, name: "tik_tok", description: "", link: "" },
  {
    stack: ["reactjs"],
    key: 6,
    name: "Military terrain passability ",
    description: "",
    link: "",
  },
  {
    stack: ["reactjs"],
    key: 7,
    name: "AI river project",
    description: "",
    link: "",
  },
  {
    stack: ["reactjs"],
    key: 8,
    name: "DRONE attack simulator",
    description: "",
    link: "",
  },
  {
    stack: ["reactjs"],
    key: 9,
    name: "K-mean Clustering in science",
    description: "",
    link: "",
  },
  {
    stack: ["reactjs"],
    key: 10,
    name: "hillshader",
    description: "",
    link: "",
  },
  {
    stack: ["reactjs"],
    key: 11,
    name: "ortophotomap",
    description: "",
    link: "",
  },
];
